apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  annotations:
    github.com/project-slug: backstage-github-action
    # github.com/project-slug: chosam2/backstage-template
    backstage.io/techdocs-ref: dir:.
    github.com/workflows: instance.yml
  title: '${{ values.name | dump }} / EC2 instance'
  description: 'An example of a Instance Creation.'
spec:
  type: service
  owner: guests
  lifecycle: experimental